# Generated by Django 5.2.6 on 2025-09-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Car Name', max_length=255)),
                ('brand', models.CharField(help_text='Car Brand', max_length=100)),
                ('model_year', models.IntegerField(help_text='Manufacturing Year')),
                ('price', models.DecimalField(decimal_places=2, help_text='Car Price', max_digits=10)),
                ('fuel_type', models.CharField(help_text='Fuel Type (Petrol/Diesel/Electric)', max_length=50)),
                ('seating_capacity', models.IntegerField(help_text='Seating Capacity')),
            ],
        ),
    ]
